# =============================================================================
# azure-golden-image-factory / packer-windows / windows-server-2022.pkr.hcl
#
# Builds a CIS Level 1 hardened Windows Server 2022 golden image and publishes
# it to the Azure Compute Gallery shared with Ubuntu and RHEL builds.
#
# Variable names are intentionally aligned with the PKR_VAR_* environment
# variables set by the Golden Image Factory pipeline (golden-image-pipeline.yml)
# so no extra mapping is needed in CI.
#
# Provisioner order — do not reorder:
#   1. bootstrap-winrm.ps1           Keep WinRM alive for Ansible
#   2. windows-update                Patch Tuesday updates before hardening
#   3. ansible (--skip winrm_conn)   CIS L1 main pass; WinRM-killers skipped
#   4. windows-restart               Flush GPO/registry writes to disk
#   5. apply-winrm-cis-controls.ps1  Apply WinRM-disabling controls via registry
#   6. run-compliance-scan.ps1       Bake compliance report into image
#   7. sysprep.ps1                   Generalize — must be last
# =============================================================================

packer {
  required_version = ">= 1.9.0"

  required_plugins {
    huaweicloud = {
      version = ">= 1.2.0"
      source  = "github.com/huaweicloud/huaweicloud"
    }
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
    windows-update = {
      source  = "github.com/rgl/windows-update"
      version = "~> 0.14"
    }
  }
}

# =============================================================================
# Variables — names match PKR_VAR_* set in golden-image-pipeline.yml env block
# =============================================================================
# Matches PKR_VAR_resource_group set in the pipeline env block.
# Used for both the ephemeral build VM and the Compute Gallery — same RG as
# Ubuntu/RHEL builds for consistency.


# These two are declared so Packer doesn't warn about unknown PKR_VAR_* values
# injected by the shared pipeline env block. They are not used for Windows builds
# because azure-arm manages its own WinRM credentials dynamically.

variable "local_admin_username" {
  type    = string
  default = "sysadmin"
}
variable "local_admin_password" {
  type      = string
  sensitive = true
}


# =============================================================================
# Locals
# =============================================================================

locals {
  timestamp  = formatdate("YYYYMMDD-hhmmss", timestamp())
  image_name = "win2022-cis-l1-${local.timestamp}"

  # Ansible extra-args injected into every ansible provisioner call.
  # build.Password is the dynamic WinRM password generated by azure-arm —
  # passing it explicitly here is the fix for the "credentials rejected" error.
  ansible_base_args = [
    "-e", "ansible_connection=winrm",
    "-e", "ansible_winrm_scheme=https",
    "-e", "ansible_winrm_server_cert_validation=ignore",
    "-e", "ansible_winrm_transport=basic",
    "-e", "ansible_winrm_operation_timeout_sec=120",
    "-e", "ansible_winrm_read_timeout_sec=150",
    "-e", "ansible_user=${var.local_admin_username}"
  ]
}

# =============================================================================
# Source
# =============================================================================

source "huaweicloud-ecs" "win2022_cis_l1" {
  # Auth
  access_key  = var.hw_access_key
  secret_key  = var.hw_secret_key
  project_id  = var.hw_project_id
  region      = var.hw_region
  auth_url    = "https://iam.my-kualalumpur-1.alphaedge.tmone.com.my/v3"
  insecure    = true

  source_image_name = "Windows Server 2022 Standard 64bit English"
  flavor            = "c6.large.2"

  vpc_id          = var.hw_vpc_id
  subnets         = [var.hw_subnet_id]
  security_groups = [var.hw_security_group_id]

  eip_type           = "5_bgp"
  eip_bandwidth_size = 5

  image_name_target = "win2022-cis-l1-${var.image_version}"
  image_tags = {
    OS          = "Windows Server 2022"
    Compliance  = "CIS-Level-1"
    ManagedBy   = "Packer-Ansible-Pipeline"
    BuildDate   = "{{timestamp}}"
  }


  # Communicator: WinRM over HTTPS (azure-arm bootstraps the cert automatically)
  communicator   = "winrm"
  winrm_use_ssl  = true
  winrm_insecure = true
  winrm_timeout  = "30m"
  winrm_username = var.local_admin_username
  winrm_password = var.local_admin_password

  user_data_file = "${path.root}/scripts/bootstrap-winrm.ps1"



  shared_image_gallery_destination {
    gallery_name        = var.gallery_name
    image_name          = var.image_definition_name
    image_version       = var.image_version
    resource_group      = var.resource_group
    replication_regions = var.replication_regions
  }

  azure_tags = var.tags
}

# =============================================================================
# Build
# =============================================================================

build {
  sources = ["source.huaweicloud-ecs.win2022_cis_l1"]

  # Step 1 — Re-enforce WinRM before Ansible connects.
  # Azure images can silently reset WinRM config during first-boot scripts.
  provisioner "powershell" {
    script = "${path.root}/../packer-windows/scripts/bootstrap-winrm.ps1"
  }
  
  provisioner "powershell" {
    elevated_user     = build.User
    elevated_password = build.Password
    inline = [
      "Write-Output 'Installing OpenSSH Server...'",
      "Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0"
    ]
  }

  # Step 3 — CIS L1 main hardening pass.
  # --skip-tags winrm_connectivity defers the two controls that would kill
  # the Ansible WinRM connection (18.9.102.2.2 and 18.9.103.1).
  provisioner "ansible" {
    playbook_file   = "${path.root}/../ansible/windows-cis-l1.yml"
    user            = var.local_admin_username
    use_proxy       = false
    extra_arguments = concat(local.ansible_base_args, [
      "-e", "ansible_password=${build.Password}", # <--- THE FIX: Moved it here!
      "--skip-tags", "winrm_connectivity",
      "-e", "@${path.root}/../ansible/cis-overrides.yml"
    ])
  }

  # Step 4 — Restart after CIS hardening.
  # Without this restart, registry/GPO writes from the CIS role are not
  # fully committed — the compliance scan will report false failures.
  provisioner "windows-restart" {
    restart_timeout       = "15m"
    restart_check_command = "powershell -command \"& {Write-Output 'restarted'}\""
  }

  provisioner "powershell" {
    inline = [
      "Write-Output 'Creating sysadmin local admin account...'",
      "$pw = ConvertTo-SecureString '${var.local_admin_password}' -AsPlainText -Force",
      "New-LocalUser -Name 'sysadmin' -Password $pw -PasswordNeverExpires -AccountNeverExpires -ErrorAction SilentlyContinue | Out-Null",
      "Add-LocalGroupMember -Group 'Administrators' -Member 'sysadmin' -ErrorAction SilentlyContinue",
      "Write-Output 'sysadmin created and added to Administrators.'",

      # Manually create the profile directory structure
      # Windows will flesh it out on first real login, but the directory
      # existing is enough for the SSH key injection script to work
      "New-Item -ItemType Directory -Force -Path 'C:\\Users\\sysadmin\\.ssh' | Out-Null",
      "Write-Output 'Profile skeleton created at C:\\Users\\sysadmin'"
    ]
  }

  # Step 4.5 — Inject the extracted CIS Gold Standard configuration files.
  # This makes the .inf, .csv, and .reg files available to finalize.ps1
  # at C:\Windows\Setup\Scripts\ on the ephemeral VM.
  provisioner "file" {
    source      = "${path.root}/files/"
    destination = "C:/Windows/Setup/Scripts/"
  }

  # Step 5 — Apply WinRM-disabling CIS controls via direct registry writes.
  # These two controls cannot run through Ansible because they cut the session.
  # Done last, via PowerShell, with no active WinRM dependency.
  provisioner "powershell" { 
    script = "${path.root}/../packer-windows/scripts/finalize.ps1"
  }

  post-processor "manifest" {
    output     = "${path.root}/manifest.json"
    strip_path = true
    custom_data = {
      image_name    = local.image_name
      image_version = var.image_version
      cis_level     = "L1"
      build_date    = local.timestamp
    }
  }
}